name: Deploy to ECR

on:
  workflow_run:
    workflows: ["UnitTest"]
    types:
      - completed

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(sed -ne "s/.*VERSION = //p" main.py | tr -d '"')"

    - name: Print VERSION
      run: echo "Version is ${{ steps.getversion.outputs.version }}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: angitest_dev-repo
        IMAGE_TAG: ${{ steps.getversion.outputs.version }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG