name: UnitTest

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unitTest:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Setup python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.5'
        architecture: 'x64'
    
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: pytest test.py
